services:
  postgresql:
    image: postgres:14-alpine
    restart: always
    volumes:
      - ./PGDATA/:/var/lib/postgresql/data
    ports:
      - "8032:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
